# fly.toml app configuration file generated for scrapyd on 2024-04-17T14:16:45+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'scrapyd'
primary_region = 'syd'

[[mounts]]
  source = 'scrapyd'
  destination = '/data'
  initial_size = '1g'

[[vm]]
  size = 'shared-cpu-1x'

[checks]
  [checks.daemon]
    port = 6800
    type = "http"
    method = "get"
    path = "/daemonstatus.json"
